# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f527f9117a7e62dd0ed03ad49636d300f3b8896619a14d877c020b12c19d594416c38e0ba89c5c8518ebb115a60d3c3bb8b2d1729d82be8fa3c42fc158916c63

test:
  secret_key_base: 1e453d1280f51f105e208e97abf60652d939be0ad5db5621beecd61c4ed8e2c1a90a1d8fb2b1a945533d275ac4c45a8ccd6bf0cf80561ca4666341651dfdad76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
